DetectionModel:
  model_type: "yolov5"
  class_names_path: ./model_data/coco_names.txt
  model_path: ./model_data/yolov5s.onnx
  input_shape: [1, 3,640,640]
  engine_type: 'tensorrt'
  #engine_type: 'onnx'
  engine_mode: "fp16"
  calibrator_image_dir: None
  calibrator_cache_path: None
  confidence_threshold: 0.3
  iou_threshold: 0.45

log_path: "./log.log"

