DetectionModel:
  model_type: "yolov4"
  class_name_path: ./model_data/coco_names.txt
  engine_model_path: ./model_data/yolov4_tiny.onnx
  input_shape: [1,3,640,640]
  engine_type: 'onnx'
  confidence_threshold: 0.3
  iou_threshold: 0.45

log_path: "./log.log"

