DetectionModel:
  model_type: "yolos"
  class_name_path: ./model_data/coco_names.txt
  engine_model_path: ./model_data/yolos_base_800x800.onnx
  input_shape: [1, 3,800,800]
  engine_type: 'onnx'
  confidence_threshold: 0.3
  iou_threshold: 0.45

log_path: "./log.log"

